name: CI/CD Pipeline with Email

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci
      - run: npm test

      - name: Build app
        run: npm run build || echo "No build script defined"
        
      - name: Trigger and Monitor Render Deployment
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # Trigger deploy
          curl -X POST "$RENDER_DEPLOY_HOOK"

          # Poll for deployment status
          for i in {1..30}; do
            echo "Checking deployment status... attempt $i"
            STATUS=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
              https://api.render.com/v1/services/$SERVICE_ID/deploys | jq -r '.[0].status')

            echo "Status: $STATUS"

            if [[ "$STATUS" == "live" ]]; then
              echo "✅ Render deployment successful"
              exit 0
            elif [[ "$STATUS" == "failed" ]]; then
              echo "❌ Render deployment failed"
              exit 1
            fi

            sleep 10
          done

          echo "❌ Timed out waiting for deployment"
          exit 1


      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Deployment Complete: Node.js App"
          to: maheshanekallu@gmail.com
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            🚀 Hello Mahesh!!

            Your application was just deployed successfully.

            🔗 Live URL: https://node-cicd-q6g2.onrender.com/
